server.port=8083

# In-Memory H2 Database for instant zero-config local execution
spring.datasource.url=jdbc:h2:mem:jio_customer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Downstream service URLs
services.tmf632.url=http://localhost:8082
services.tmf681.url=http://localhost:8088
