spring.application.name=payment-management-service

server.port=8080

spring.datasource.url=jdbc:mariadb://host.docker.internal:3306/apex_payment

spring.datasource.username=root

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true